name: CI
on: push
jobs:
  compile:
    strategy:
      matrix:
        runner: [macos-latest, macos-10.15]
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v2
    - run: make
